services:
  nextcloud-db:
    image: mariadb:11.4
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW # --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - <YOUR-MYSQL-DIRECTORY>/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<CHANGE-THIS-1>
      - MYSQL_PASSWORD=<CHANGE-THIS-2>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud-cron-ffmpeg-pdlib:latest
    restart: always
    ports:
      - 9196:80
    links:
      - nextcloud-db
    volumes:
      - <YOUR-HTML-DIRECTORY>/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=<CHANGE-THIS-2>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://<YOUR-NEXTCLOUD-DOMAIN>
networks: {}