name: Docker Image CI

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd nextcloud-dockerfile && docker build . --file Dockerfile --tag nextcloud-cron-ffmpeg-pdlib:$(date +%s) --tag nextcloud-cron-ffmpeg-pdlib:latest
